//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from CIL.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace ILAssembler {
using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="CILParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public interface ICILListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="CILParser.id"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterId([NotNull] CILParser.IdContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CILParser.id"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitId([NotNull] CILParser.IdContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CILParser.dottedName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDottedName([NotNull] CILParser.DottedNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CILParser.dottedName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDottedName([NotNull] CILParser.DottedNameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CILParser.compQstring"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCompQstring([NotNull] CILParser.CompQstringContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CILParser.compQstring"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCompQstring([NotNull] CILParser.CompQstringContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CILParser.decls"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDecls([NotNull] CILParser.DeclsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CILParser.decls"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDecls([NotNull] CILParser.DeclsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CILParser.decl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDecl([NotNull] CILParser.DeclContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CILParser.decl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDecl([NotNull] CILParser.DeclContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CILParser.subsystem"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSubsystem([NotNull] CILParser.SubsystemContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CILParser.subsystem"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSubsystem([NotNull] CILParser.SubsystemContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CILParser.corflags"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCorflags([NotNull] CILParser.CorflagsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CILParser.corflags"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCorflags([NotNull] CILParser.CorflagsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CILParser.alignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAlignment([NotNull] CILParser.AlignmentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CILParser.alignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAlignment([NotNull] CILParser.AlignmentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CILParser.imagebase"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterImagebase([NotNull] CILParser.ImagebaseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CILParser.imagebase"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitImagebase([NotNull] CILParser.ImagebaseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CILParser.stackreserve"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStackreserve([NotNull] CILParser.StackreserveContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CILParser.stackreserve"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStackreserve([NotNull] CILParser.StackreserveContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CILParser.assemblyBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssemblyBlock([NotNull] CILParser.AssemblyBlockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CILParser.assemblyBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssemblyBlock([NotNull] CILParser.AssemblyBlockContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CILParser.mscorlib"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMscorlib([NotNull] CILParser.MscorlibContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CILParser.mscorlib"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMscorlib([NotNull] CILParser.MscorlibContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CILParser.languageDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLanguageDecl([NotNull] CILParser.LanguageDeclContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CILParser.languageDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLanguageDecl([NotNull] CILParser.LanguageDeclContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CILParser.typelist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypelist([NotNull] CILParser.TypelistContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CILParser.typelist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypelist([NotNull] CILParser.TypelistContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CILParser.int32"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInt32([NotNull] CILParser.Int32Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CILParser.int32"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInt32([NotNull] CILParser.Int32Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CILParser.int64"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInt64([NotNull] CILParser.Int64Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CILParser.int64"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInt64([NotNull] CILParser.Int64Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CILParser.float64"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFloat64([NotNull] CILParser.Float64Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CILParser.float64"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFloat64([NotNull] CILParser.Float64Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CILParser.intOrWildcard"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIntOrWildcard([NotNull] CILParser.IntOrWildcardContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CILParser.intOrWildcard"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIntOrWildcard([NotNull] CILParser.IntOrWildcardContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CILParser.compControl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCompControl([NotNull] CILParser.CompControlContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CILParser.compControl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCompControl([NotNull] CILParser.CompControlContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CILParser.typedefDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypedefDecl([NotNull] CILParser.TypedefDeclContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CILParser.typedefDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypedefDecl([NotNull] CILParser.TypedefDeclContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CILParser.customDescr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCustomDescr([NotNull] CILParser.CustomDescrContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CILParser.customDescr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCustomDescr([NotNull] CILParser.CustomDescrContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CILParser.customDescrWithOwner"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCustomDescrWithOwner([NotNull] CILParser.CustomDescrWithOwnerContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CILParser.customDescrWithOwner"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCustomDescrWithOwner([NotNull] CILParser.CustomDescrWithOwnerContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CILParser.customType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCustomType([NotNull] CILParser.CustomTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CILParser.customType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCustomType([NotNull] CILParser.CustomTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CILParser.ownerType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOwnerType([NotNull] CILParser.OwnerTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CILParser.ownerType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOwnerType([NotNull] CILParser.OwnerTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CILParser.customBlobDescr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCustomBlobDescr([NotNull] CILParser.CustomBlobDescrContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CILParser.customBlobDescr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCustomBlobDescr([NotNull] CILParser.CustomBlobDescrContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CILParser.customBlobArgs"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCustomBlobArgs([NotNull] CILParser.CustomBlobArgsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CILParser.customBlobArgs"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCustomBlobArgs([NotNull] CILParser.CustomBlobArgsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CILParser.customBlobNVPairs"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCustomBlobNVPairs([NotNull] CILParser.CustomBlobNVPairsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CILParser.customBlobNVPairs"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCustomBlobNVPairs([NotNull] CILParser.CustomBlobNVPairsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CILParser.fieldOrProp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFieldOrProp([NotNull] CILParser.FieldOrPropContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CILParser.fieldOrProp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFieldOrProp([NotNull] CILParser.FieldOrPropContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CILParser.serializType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSerializType([NotNull] CILParser.SerializTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CILParser.serializType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSerializType([NotNull] CILParser.SerializTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CILParser.serializTypeElement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSerializTypeElement([NotNull] CILParser.SerializTypeElementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CILParser.serializTypeElement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSerializTypeElement([NotNull] CILParser.SerializTypeElementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CILParser.moduleHead"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterModuleHead([NotNull] CILParser.ModuleHeadContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CILParser.moduleHead"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitModuleHead([NotNull] CILParser.ModuleHeadContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CILParser.vtfixupDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVtfixupDecl([NotNull] CILParser.VtfixupDeclContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CILParser.vtfixupDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVtfixupDecl([NotNull] CILParser.VtfixupDeclContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CILParser.vtfixupAttr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVtfixupAttr([NotNull] CILParser.VtfixupAttrContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CILParser.vtfixupAttr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVtfixupAttr([NotNull] CILParser.VtfixupAttrContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CILParser.vtableDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVtableDecl([NotNull] CILParser.VtableDeclContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CILParser.vtableDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVtableDecl([NotNull] CILParser.VtableDeclContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CILParser.nameSpaceHead"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNameSpaceHead([NotNull] CILParser.NameSpaceHeadContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CILParser.nameSpaceHead"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNameSpaceHead([NotNull] CILParser.NameSpaceHeadContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CILParser.classHead"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterClassHead([NotNull] CILParser.ClassHeadContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CILParser.classHead"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitClassHead([NotNull] CILParser.ClassHeadContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CILParser.classAttr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterClassAttr([NotNull] CILParser.ClassAttrContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CILParser.classAttr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitClassAttr([NotNull] CILParser.ClassAttrContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CILParser.extendsClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExtendsClause([NotNull] CILParser.ExtendsClauseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CILParser.extendsClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExtendsClause([NotNull] CILParser.ExtendsClauseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CILParser.implClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterImplClause([NotNull] CILParser.ImplClauseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CILParser.implClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitImplClause([NotNull] CILParser.ImplClauseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CILParser.classDecls"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterClassDecls([NotNull] CILParser.ClassDeclsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CILParser.classDecls"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitClassDecls([NotNull] CILParser.ClassDeclsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CILParser.implList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterImplList([NotNull] CILParser.ImplListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CILParser.implList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitImplList([NotNull] CILParser.ImplListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CILParser.esHead"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEsHead([NotNull] CILParser.EsHeadContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CILParser.esHead"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEsHead([NotNull] CILParser.EsHeadContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CILParser.extSourceSpec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExtSourceSpec([NotNull] CILParser.ExtSourceSpecContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CILParser.extSourceSpec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExtSourceSpec([NotNull] CILParser.ExtSourceSpecContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CILParser.fileDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFileDecl([NotNull] CILParser.FileDeclContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CILParser.fileDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFileDecl([NotNull] CILParser.FileDeclContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CILParser.fileAttr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFileAttr([NotNull] CILParser.FileAttrContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CILParser.fileAttr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFileAttr([NotNull] CILParser.FileAttrContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CILParser.fileEntry"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFileEntry([NotNull] CILParser.FileEntryContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CILParser.fileEntry"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFileEntry([NotNull] CILParser.FileEntryContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CILParser.asmAttrAny"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAsmAttrAny([NotNull] CILParser.AsmAttrAnyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CILParser.asmAttrAny"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAsmAttrAny([NotNull] CILParser.AsmAttrAnyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CILParser.asmAttr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAsmAttr([NotNull] CILParser.AsmAttrContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CILParser.asmAttr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAsmAttr([NotNull] CILParser.AsmAttrContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CILParser.instr_none"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInstr_none([NotNull] CILParser.Instr_noneContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CILParser.instr_none"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInstr_none([NotNull] CILParser.Instr_noneContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CILParser.instr_var"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInstr_var([NotNull] CILParser.Instr_varContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CILParser.instr_var"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInstr_var([NotNull] CILParser.Instr_varContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CILParser.instr_i"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInstr_i([NotNull] CILParser.Instr_iContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CILParser.instr_i"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInstr_i([NotNull] CILParser.Instr_iContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CILParser.instr_i8"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInstr_i8([NotNull] CILParser.Instr_i8Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CILParser.instr_i8"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInstr_i8([NotNull] CILParser.Instr_i8Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CILParser.instr_r"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInstr_r([NotNull] CILParser.Instr_rContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CILParser.instr_r"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInstr_r([NotNull] CILParser.Instr_rContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CILParser.instr_brtarget"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInstr_brtarget([NotNull] CILParser.Instr_brtargetContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CILParser.instr_brtarget"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInstr_brtarget([NotNull] CILParser.Instr_brtargetContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CILParser.instr_method"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInstr_method([NotNull] CILParser.Instr_methodContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CILParser.instr_method"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInstr_method([NotNull] CILParser.Instr_methodContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CILParser.instr_field"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInstr_field([NotNull] CILParser.Instr_fieldContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CILParser.instr_field"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInstr_field([NotNull] CILParser.Instr_fieldContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CILParser.instr_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInstr_type([NotNull] CILParser.Instr_typeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CILParser.instr_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInstr_type([NotNull] CILParser.Instr_typeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CILParser.instr_string"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInstr_string([NotNull] CILParser.Instr_stringContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CILParser.instr_string"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInstr_string([NotNull] CILParser.Instr_stringContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CILParser.instr_sig"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInstr_sig([NotNull] CILParser.Instr_sigContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CILParser.instr_sig"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInstr_sig([NotNull] CILParser.Instr_sigContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CILParser.instr_tok"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInstr_tok([NotNull] CILParser.Instr_tokContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CILParser.instr_tok"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInstr_tok([NotNull] CILParser.Instr_tokContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CILParser.instr_switch"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInstr_switch([NotNull] CILParser.Instr_switchContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CILParser.instr_switch"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInstr_switch([NotNull] CILParser.Instr_switchContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CILParser.instr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInstr([NotNull] CILParser.InstrContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CILParser.instr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInstr([NotNull] CILParser.InstrContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CILParser.labels"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLabels([NotNull] CILParser.LabelsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CILParser.labels"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLabels([NotNull] CILParser.LabelsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CILParser.typeArgs"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeArgs([NotNull] CILParser.TypeArgsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CILParser.typeArgs"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeArgs([NotNull] CILParser.TypeArgsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CILParser.bounds"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBounds([NotNull] CILParser.BoundsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CILParser.bounds"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBounds([NotNull] CILParser.BoundsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CILParser.sigArgs"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSigArgs([NotNull] CILParser.SigArgsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CILParser.sigArgs"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSigArgs([NotNull] CILParser.SigArgsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CILParser.sigArg"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSigArg([NotNull] CILParser.SigArgContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CILParser.sigArg"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSigArg([NotNull] CILParser.SigArgContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CILParser.className"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterClassName([NotNull] CILParser.ClassNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CILParser.className"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitClassName([NotNull] CILParser.ClassNameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CILParser.slashedName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSlashedName([NotNull] CILParser.SlashedNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CILParser.slashedName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSlashedName([NotNull] CILParser.SlashedNameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CILParser.assemblyDecls"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssemblyDecls([NotNull] CILParser.AssemblyDeclsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CILParser.assemblyDecls"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssemblyDecls([NotNull] CILParser.AssemblyDeclsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CILParser.assemblyDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssemblyDecl([NotNull] CILParser.AssemblyDeclContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CILParser.assemblyDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssemblyDecl([NotNull] CILParser.AssemblyDeclContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CILParser.typeSpec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeSpec([NotNull] CILParser.TypeSpecContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CILParser.typeSpec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeSpec([NotNull] CILParser.TypeSpecContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CILParser.nativeType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNativeType([NotNull] CILParser.NativeTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CILParser.nativeType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNativeType([NotNull] CILParser.NativeTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>PointerNativeType</c>
	/// labeled alternative in <see cref="CILParser.nativeTypeArrayPointerInfo"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPointerNativeType([NotNull] CILParser.PointerNativeTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>PointerNativeType</c>
	/// labeled alternative in <see cref="CILParser.nativeTypeArrayPointerInfo"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPointerNativeType([NotNull] CILParser.PointerNativeTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>PointerArrayTypeNoSizeData</c>
	/// labeled alternative in <see cref="CILParser.nativeTypeArrayPointerInfo"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPointerArrayTypeNoSizeData([NotNull] CILParser.PointerArrayTypeNoSizeDataContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>PointerArrayTypeNoSizeData</c>
	/// labeled alternative in <see cref="CILParser.nativeTypeArrayPointerInfo"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPointerArrayTypeNoSizeData([NotNull] CILParser.PointerArrayTypeNoSizeDataContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>PointerArrayTypeSize</c>
	/// labeled alternative in <see cref="CILParser.nativeTypeArrayPointerInfo"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPointerArrayTypeSize([NotNull] CILParser.PointerArrayTypeSizeContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>PointerArrayTypeSize</c>
	/// labeled alternative in <see cref="CILParser.nativeTypeArrayPointerInfo"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPointerArrayTypeSize([NotNull] CILParser.PointerArrayTypeSizeContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>PointerArrayTypeSizeParamIndex</c>
	/// labeled alternative in <see cref="CILParser.nativeTypeArrayPointerInfo"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPointerArrayTypeSizeParamIndex([NotNull] CILParser.PointerArrayTypeSizeParamIndexContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>PointerArrayTypeSizeParamIndex</c>
	/// labeled alternative in <see cref="CILParser.nativeTypeArrayPointerInfo"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPointerArrayTypeSizeParamIndex([NotNull] CILParser.PointerArrayTypeSizeParamIndexContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>PointerArrayTypeParamIndex</c>
	/// labeled alternative in <see cref="CILParser.nativeTypeArrayPointerInfo"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPointerArrayTypeParamIndex([NotNull] CILParser.PointerArrayTypeParamIndexContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>PointerArrayTypeParamIndex</c>
	/// labeled alternative in <see cref="CILParser.nativeTypeArrayPointerInfo"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPointerArrayTypeParamIndex([NotNull] CILParser.PointerArrayTypeParamIndexContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CILParser.nativeTypeElement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNativeTypeElement([NotNull] CILParser.NativeTypeElementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CILParser.nativeTypeElement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNativeTypeElement([NotNull] CILParser.NativeTypeElementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CILParser.iidParamIndex"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIidParamIndex([NotNull] CILParser.IidParamIndexContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CILParser.iidParamIndex"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIidParamIndex([NotNull] CILParser.IidParamIndexContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CILParser.variantType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVariantType([NotNull] CILParser.VariantTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CILParser.variantType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVariantType([NotNull] CILParser.VariantTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CILParser.variantTypeElement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVariantTypeElement([NotNull] CILParser.VariantTypeElementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CILParser.variantTypeElement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVariantTypeElement([NotNull] CILParser.VariantTypeElementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CILParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterType([NotNull] CILParser.TypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CILParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitType([NotNull] CILParser.TypeContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>SZArrayModifier</c>
	/// labeled alternative in <see cref="CILParser.typeModifiers"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSZArrayModifier([NotNull] CILParser.SZArrayModifierContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>SZArrayModifier</c>
	/// labeled alternative in <see cref="CILParser.typeModifiers"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSZArrayModifier([NotNull] CILParser.SZArrayModifierContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ArrayModifier</c>
	/// labeled alternative in <see cref="CILParser.typeModifiers"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArrayModifier([NotNull] CILParser.ArrayModifierContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ArrayModifier</c>
	/// labeled alternative in <see cref="CILParser.typeModifiers"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArrayModifier([NotNull] CILParser.ArrayModifierContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ByRefModifier</c>
	/// labeled alternative in <see cref="CILParser.typeModifiers"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterByRefModifier([NotNull] CILParser.ByRefModifierContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ByRefModifier</c>
	/// labeled alternative in <see cref="CILParser.typeModifiers"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitByRefModifier([NotNull] CILParser.ByRefModifierContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>PtrModifier</c>
	/// labeled alternative in <see cref="CILParser.typeModifiers"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPtrModifier([NotNull] CILParser.PtrModifierContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>PtrModifier</c>
	/// labeled alternative in <see cref="CILParser.typeModifiers"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPtrModifier([NotNull] CILParser.PtrModifierContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>PinnedModifier</c>
	/// labeled alternative in <see cref="CILParser.typeModifiers"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPinnedModifier([NotNull] CILParser.PinnedModifierContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>PinnedModifier</c>
	/// labeled alternative in <see cref="CILParser.typeModifiers"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPinnedModifier([NotNull] CILParser.PinnedModifierContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>RequiredModifier</c>
	/// labeled alternative in <see cref="CILParser.typeModifiers"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRequiredModifier([NotNull] CILParser.RequiredModifierContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>RequiredModifier</c>
	/// labeled alternative in <see cref="CILParser.typeModifiers"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRequiredModifier([NotNull] CILParser.RequiredModifierContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>OptionalModifier</c>
	/// labeled alternative in <see cref="CILParser.typeModifiers"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOptionalModifier([NotNull] CILParser.OptionalModifierContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>OptionalModifier</c>
	/// labeled alternative in <see cref="CILParser.typeModifiers"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOptionalModifier([NotNull] CILParser.OptionalModifierContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>GenericArgumentsModifier</c>
	/// labeled alternative in <see cref="CILParser.typeModifiers"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGenericArgumentsModifier([NotNull] CILParser.GenericArgumentsModifierContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>GenericArgumentsModifier</c>
	/// labeled alternative in <see cref="CILParser.typeModifiers"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGenericArgumentsModifier([NotNull] CILParser.GenericArgumentsModifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CILParser.elementType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterElementType([NotNull] CILParser.ElementTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CILParser.elementType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitElementType([NotNull] CILParser.ElementTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CILParser.simpleType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSimpleType([NotNull] CILParser.SimpleTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CILParser.simpleType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSimpleType([NotNull] CILParser.SimpleTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CILParser.bound"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBound([NotNull] CILParser.BoundContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CILParser.bound"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBound([NotNull] CILParser.BoundContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CILParser.secDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSecDecl([NotNull] CILParser.SecDeclContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CILParser.secDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSecDecl([NotNull] CILParser.SecDeclContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CILParser.secAttrSetBlob"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSecAttrSetBlob([NotNull] CILParser.SecAttrSetBlobContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CILParser.secAttrSetBlob"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSecAttrSetBlob([NotNull] CILParser.SecAttrSetBlobContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CILParser.secAttrBlob"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSecAttrBlob([NotNull] CILParser.SecAttrBlobContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CILParser.secAttrBlob"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSecAttrBlob([NotNull] CILParser.SecAttrBlobContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CILParser.nameValPairs"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNameValPairs([NotNull] CILParser.NameValPairsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CILParser.nameValPairs"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNameValPairs([NotNull] CILParser.NameValPairsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CILParser.nameValPair"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNameValPair([NotNull] CILParser.NameValPairContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CILParser.nameValPair"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNameValPair([NotNull] CILParser.NameValPairContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CILParser.truefalse"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTruefalse([NotNull] CILParser.TruefalseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CILParser.truefalse"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTruefalse([NotNull] CILParser.TruefalseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CILParser.caValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCaValue([NotNull] CILParser.CaValueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CILParser.caValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCaValue([NotNull] CILParser.CaValueContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CILParser.secAction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSecAction([NotNull] CILParser.SecActionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CILParser.secAction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSecAction([NotNull] CILParser.SecActionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CILParser.methodRef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMethodRef([NotNull] CILParser.MethodRefContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CILParser.methodRef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMethodRef([NotNull] CILParser.MethodRefContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CILParser.callConv"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCallConv([NotNull] CILParser.CallConvContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CILParser.callConv"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCallConv([NotNull] CILParser.CallConvContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CILParser.callKind"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCallKind([NotNull] CILParser.CallKindContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CILParser.callKind"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCallKind([NotNull] CILParser.CallKindContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CILParser.mdtoken"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMdtoken([NotNull] CILParser.MdtokenContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CILParser.mdtoken"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMdtoken([NotNull] CILParser.MdtokenContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CILParser.memberRef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMemberRef([NotNull] CILParser.MemberRefContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CILParser.memberRef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMemberRef([NotNull] CILParser.MemberRefContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CILParser.fieldRef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFieldRef([NotNull] CILParser.FieldRefContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CILParser.fieldRef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFieldRef([NotNull] CILParser.FieldRefContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CILParser.typeList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeList([NotNull] CILParser.TypeListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CILParser.typeList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeList([NotNull] CILParser.TypeListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CILParser.typarsClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTyparsClause([NotNull] CILParser.TyparsClauseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CILParser.typarsClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTyparsClause([NotNull] CILParser.TyparsClauseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CILParser.typarAttrib"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTyparAttrib([NotNull] CILParser.TyparAttribContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CILParser.typarAttrib"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTyparAttrib([NotNull] CILParser.TyparAttribContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CILParser.typarAttribs"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTyparAttribs([NotNull] CILParser.TyparAttribsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CILParser.typarAttribs"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTyparAttribs([NotNull] CILParser.TyparAttribsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CILParser.typar"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypar([NotNull] CILParser.TyparContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CILParser.typar"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypar([NotNull] CILParser.TyparContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CILParser.typars"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypars([NotNull] CILParser.TyparsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CILParser.typars"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypars([NotNull] CILParser.TyparsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CILParser.tyBound"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTyBound([NotNull] CILParser.TyBoundContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CILParser.tyBound"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTyBound([NotNull] CILParser.TyBoundContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CILParser.genArity"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGenArity([NotNull] CILParser.GenArityContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CILParser.genArity"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGenArity([NotNull] CILParser.GenArityContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CILParser.genArityNotEmpty"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGenArityNotEmpty([NotNull] CILParser.GenArityNotEmptyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CILParser.genArityNotEmpty"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGenArityNotEmpty([NotNull] CILParser.GenArityNotEmptyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CILParser.classDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterClassDecl([NotNull] CILParser.ClassDeclContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CILParser.classDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitClassDecl([NotNull] CILParser.ClassDeclContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CILParser.fieldDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFieldDecl([NotNull] CILParser.FieldDeclContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CILParser.fieldDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFieldDecl([NotNull] CILParser.FieldDeclContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CILParser.fieldAttr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFieldAttr([NotNull] CILParser.FieldAttrContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CILParser.fieldAttr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFieldAttr([NotNull] CILParser.FieldAttrContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CILParser.atOpt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAtOpt([NotNull] CILParser.AtOptContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CILParser.atOpt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAtOpt([NotNull] CILParser.AtOptContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CILParser.initOpt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInitOpt([NotNull] CILParser.InitOptContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CILParser.initOpt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInitOpt([NotNull] CILParser.InitOptContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CILParser.repeatOpt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRepeatOpt([NotNull] CILParser.RepeatOptContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CILParser.repeatOpt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRepeatOpt([NotNull] CILParser.RepeatOptContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CILParser.eventHead"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEventHead([NotNull] CILParser.EventHeadContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CILParser.eventHead"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEventHead([NotNull] CILParser.EventHeadContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CILParser.eventAttr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEventAttr([NotNull] CILParser.EventAttrContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CILParser.eventAttr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEventAttr([NotNull] CILParser.EventAttrContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CILParser.eventDecls"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEventDecls([NotNull] CILParser.EventDeclsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CILParser.eventDecls"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEventDecls([NotNull] CILParser.EventDeclsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CILParser.eventDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEventDecl([NotNull] CILParser.EventDeclContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CILParser.eventDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEventDecl([NotNull] CILParser.EventDeclContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CILParser.propHead"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPropHead([NotNull] CILParser.PropHeadContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CILParser.propHead"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPropHead([NotNull] CILParser.PropHeadContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CILParser.propAttr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPropAttr([NotNull] CILParser.PropAttrContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CILParser.propAttr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPropAttr([NotNull] CILParser.PropAttrContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CILParser.propDecls"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPropDecls([NotNull] CILParser.PropDeclsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CILParser.propDecls"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPropDecls([NotNull] CILParser.PropDeclsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CILParser.propDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPropDecl([NotNull] CILParser.PropDeclContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CILParser.propDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPropDecl([NotNull] CILParser.PropDeclContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CILParser.marshalClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMarshalClause([NotNull] CILParser.MarshalClauseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CILParser.marshalClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMarshalClause([NotNull] CILParser.MarshalClauseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CILParser.marshalBlob"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMarshalBlob([NotNull] CILParser.MarshalBlobContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CILParser.marshalBlob"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMarshalBlob([NotNull] CILParser.MarshalBlobContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CILParser.paramAttr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParamAttr([NotNull] CILParser.ParamAttrContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CILParser.paramAttr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParamAttr([NotNull] CILParser.ParamAttrContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CILParser.paramAttrElement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParamAttrElement([NotNull] CILParser.ParamAttrElementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CILParser.paramAttrElement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParamAttrElement([NotNull] CILParser.ParamAttrElementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CILParser.methodHead"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMethodHead([NotNull] CILParser.MethodHeadContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CILParser.methodHead"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMethodHead([NotNull] CILParser.MethodHeadContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CILParser.methAttr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMethAttr([NotNull] CILParser.MethAttrContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CILParser.methAttr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMethAttr([NotNull] CILParser.MethAttrContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CILParser.pinvImpl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPinvImpl([NotNull] CILParser.PinvImplContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CILParser.pinvImpl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPinvImpl([NotNull] CILParser.PinvImplContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CILParser.pinvAttr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPinvAttr([NotNull] CILParser.PinvAttrContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CILParser.pinvAttr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPinvAttr([NotNull] CILParser.PinvAttrContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CILParser.methodName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMethodName([NotNull] CILParser.MethodNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CILParser.methodName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMethodName([NotNull] CILParser.MethodNameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CILParser.implAttr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterImplAttr([NotNull] CILParser.ImplAttrContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CILParser.implAttr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitImplAttr([NotNull] CILParser.ImplAttrContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CILParser.methodDecls"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMethodDecls([NotNull] CILParser.MethodDeclsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CILParser.methodDecls"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMethodDecls([NotNull] CILParser.MethodDeclsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CILParser.methodDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMethodDecl([NotNull] CILParser.MethodDeclContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CILParser.methodDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMethodDecl([NotNull] CILParser.MethodDeclContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CILParser.scopeBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterScopeBlock([NotNull] CILParser.ScopeBlockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CILParser.scopeBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitScopeBlock([NotNull] CILParser.ScopeBlockContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CILParser.sehBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSehBlock([NotNull] CILParser.SehBlockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CILParser.sehBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSehBlock([NotNull] CILParser.SehBlockContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CILParser.sehClauses"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSehClauses([NotNull] CILParser.SehClausesContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CILParser.sehClauses"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSehClauses([NotNull] CILParser.SehClausesContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CILParser.tryBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTryBlock([NotNull] CILParser.TryBlockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CILParser.tryBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTryBlock([NotNull] CILParser.TryBlockContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CILParser.sehClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSehClause([NotNull] CILParser.SehClauseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CILParser.sehClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSehClause([NotNull] CILParser.SehClauseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CILParser.filterClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFilterClause([NotNull] CILParser.FilterClauseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CILParser.filterClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFilterClause([NotNull] CILParser.FilterClauseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CILParser.catchClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCatchClause([NotNull] CILParser.CatchClauseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CILParser.catchClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCatchClause([NotNull] CILParser.CatchClauseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CILParser.finallyClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFinallyClause([NotNull] CILParser.FinallyClauseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CILParser.finallyClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFinallyClause([NotNull] CILParser.FinallyClauseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CILParser.faultClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFaultClause([NotNull] CILParser.FaultClauseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CILParser.faultClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFaultClause([NotNull] CILParser.FaultClauseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CILParser.handlerBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterHandlerBlock([NotNull] CILParser.HandlerBlockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CILParser.handlerBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitHandlerBlock([NotNull] CILParser.HandlerBlockContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CILParser.dataDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDataDecl([NotNull] CILParser.DataDeclContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CILParser.dataDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDataDecl([NotNull] CILParser.DataDeclContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CILParser.ddHead"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDdHead([NotNull] CILParser.DdHeadContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CILParser.ddHead"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDdHead([NotNull] CILParser.DdHeadContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CILParser.tls"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTls([NotNull] CILParser.TlsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CILParser.tls"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTls([NotNull] CILParser.TlsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CILParser.ddBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDdBody([NotNull] CILParser.DdBodyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CILParser.ddBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDdBody([NotNull] CILParser.DdBodyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CILParser.ddItemList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDdItemList([NotNull] CILParser.DdItemListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CILParser.ddItemList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDdItemList([NotNull] CILParser.DdItemListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CILParser.ddItemCount"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDdItemCount([NotNull] CILParser.DdItemCountContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CILParser.ddItemCount"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDdItemCount([NotNull] CILParser.DdItemCountContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CILParser.ddItem"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDdItem([NotNull] CILParser.DdItemContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CILParser.ddItem"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDdItem([NotNull] CILParser.DdItemContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CILParser.fieldSerInit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFieldSerInit([NotNull] CILParser.FieldSerInitContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CILParser.fieldSerInit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFieldSerInit([NotNull] CILParser.FieldSerInitContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CILParser.bytes"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBytes([NotNull] CILParser.BytesContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CILParser.bytes"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBytes([NotNull] CILParser.BytesContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CILParser.hexbytes"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterHexbytes([NotNull] CILParser.HexbytesContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CILParser.hexbytes"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitHexbytes([NotNull] CILParser.HexbytesContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CILParser.fieldInit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFieldInit([NotNull] CILParser.FieldInitContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CILParser.fieldInit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFieldInit([NotNull] CILParser.FieldInitContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CILParser.serInit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSerInit([NotNull] CILParser.SerInitContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CILParser.serInit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSerInit([NotNull] CILParser.SerInitContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CILParser.f32seq"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterF32seq([NotNull] CILParser.F32seqContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CILParser.f32seq"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitF32seq([NotNull] CILParser.F32seqContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CILParser.f64seq"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterF64seq([NotNull] CILParser.F64seqContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CILParser.f64seq"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitF64seq([NotNull] CILParser.F64seqContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CILParser.i64seq"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterI64seq([NotNull] CILParser.I64seqContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CILParser.i64seq"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitI64seq([NotNull] CILParser.I64seqContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CILParser.i32seq"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterI32seq([NotNull] CILParser.I32seqContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CILParser.i32seq"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitI32seq([NotNull] CILParser.I32seqContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CILParser.i16seq"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterI16seq([NotNull] CILParser.I16seqContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CILParser.i16seq"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitI16seq([NotNull] CILParser.I16seqContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CILParser.i8seq"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterI8seq([NotNull] CILParser.I8seqContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CILParser.i8seq"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitI8seq([NotNull] CILParser.I8seqContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CILParser.boolSeq"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBoolSeq([NotNull] CILParser.BoolSeqContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CILParser.boolSeq"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBoolSeq([NotNull] CILParser.BoolSeqContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CILParser.sqstringSeq"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSqstringSeq([NotNull] CILParser.SqstringSeqContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CILParser.sqstringSeq"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSqstringSeq([NotNull] CILParser.SqstringSeqContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CILParser.classSeq"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterClassSeq([NotNull] CILParser.ClassSeqContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CILParser.classSeq"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitClassSeq([NotNull] CILParser.ClassSeqContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CILParser.classSeqElement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterClassSeqElement([NotNull] CILParser.ClassSeqElementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CILParser.classSeqElement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitClassSeqElement([NotNull] CILParser.ClassSeqElementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CILParser.objSeq"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterObjSeq([NotNull] CILParser.ObjSeqContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CILParser.objSeq"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitObjSeq([NotNull] CILParser.ObjSeqContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CILParser.customAttrDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCustomAttrDecl([NotNull] CILParser.CustomAttrDeclContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CILParser.customAttrDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCustomAttrDecl([NotNull] CILParser.CustomAttrDeclContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CILParser.asmOrRefDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAsmOrRefDecl([NotNull] CILParser.AsmOrRefDeclContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CILParser.asmOrRefDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAsmOrRefDecl([NotNull] CILParser.AsmOrRefDeclContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CILParser.assemblyRefHead"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssemblyRefHead([NotNull] CILParser.AssemblyRefHeadContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CILParser.assemblyRefHead"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssemblyRefHead([NotNull] CILParser.AssemblyRefHeadContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CILParser.assemblyRefDecls"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssemblyRefDecls([NotNull] CILParser.AssemblyRefDeclsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CILParser.assemblyRefDecls"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssemblyRefDecls([NotNull] CILParser.AssemblyRefDeclsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CILParser.assemblyRefDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssemblyRefDecl([NotNull] CILParser.AssemblyRefDeclContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CILParser.assemblyRefDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssemblyRefDecl([NotNull] CILParser.AssemblyRefDeclContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CILParser.exptypeHead"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExptypeHead([NotNull] CILParser.ExptypeHeadContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CILParser.exptypeHead"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExptypeHead([NotNull] CILParser.ExptypeHeadContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CILParser.exportHead"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExportHead([NotNull] CILParser.ExportHeadContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CILParser.exportHead"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExportHead([NotNull] CILParser.ExportHeadContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CILParser.exptAttr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExptAttr([NotNull] CILParser.ExptAttrContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CILParser.exptAttr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExptAttr([NotNull] CILParser.ExptAttrContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CILParser.exptypeDecls"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExptypeDecls([NotNull] CILParser.ExptypeDeclsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CILParser.exptypeDecls"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExptypeDecls([NotNull] CILParser.ExptypeDeclsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CILParser.exptypeDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExptypeDecl([NotNull] CILParser.ExptypeDeclContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CILParser.exptypeDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExptypeDecl([NotNull] CILParser.ExptypeDeclContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CILParser.manifestResHead"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterManifestResHead([NotNull] CILParser.ManifestResHeadContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CILParser.manifestResHead"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitManifestResHead([NotNull] CILParser.ManifestResHeadContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CILParser.manresAttr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterManresAttr([NotNull] CILParser.ManresAttrContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CILParser.manresAttr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitManresAttr([NotNull] CILParser.ManresAttrContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CILParser.manifestResDecls"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterManifestResDecls([NotNull] CILParser.ManifestResDeclsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CILParser.manifestResDecls"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitManifestResDecls([NotNull] CILParser.ManifestResDeclsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CILParser.manifestResDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterManifestResDecl([NotNull] CILParser.ManifestResDeclContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CILParser.manifestResDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitManifestResDecl([NotNull] CILParser.ManifestResDeclContext context);
}
} // namespace ILAssembler
